extra_css:
  - assets/stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/win5923

copyright: Copyright &copy; 2023 - 2024 Blocka

site_name: 考研筆記-資工所 
repo_name: blocka.github.io
repo_url: https://github.com/win5923/blocka.github.io

# site_url: 
theme:
  name: material
  language: "zh-TW"
  icon:
    logo: material/bookshelf
  favicon: assets/book.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes          # When section index pages are enabled, documents can be directly attached to sections, which is particularly useful for providing overview pages.
    - navigation.instant          # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.tabs
    - navigation.sections       # Ref: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link           # Ref: https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
    - content.code.annotation
    - content.code.copy
    - navigation.footer

  palette:
  - scheme: default
    primary: blue grey # header color
    accent: deep purple
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: black # main color
    accent: deep purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
      

nav:
  - Home:
    - Introduction: index.md
  - 資料結構: data-structure/ch1.md
  - 演算法: algorithm/ch1.md
  - 計組與計結: computer-organization/ch1.md
  - 作業系統: operating-system/ch1.md
  - 線性代數: linear-algebra/ch1.md
  - 離散數學: discrete-mathematics/ch1.md
plugins:
  - search
  - blog:
      post_date_format: "yyyy/MM/dd"
  # - social:
  #     cards_layout_options:
  #       font_family: Noto Sans TC


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences # Ref: https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#configuration
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list # Ref: https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment-left
  - md_in_html   # Ref: https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment-left
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.twemoji
  - codehilite:
      css_class: highlight
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences:  # Diagrams Configuration
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format